<!DOCTYPE html>
<html>
<head>
	<title>{title}</title>
	<style type="text/css">
		body{
			font-family: 'Roboto','Verdana';
		}
		.container{
			margin: auto;
			max-width: 400px;
			padding: 20px;
			box-shadow: 5px 10px 18px #888888;
			background-color: #FFF;
		}
		.header{
			background-color: blue;
			color : #FFF;
			padding: 20px;
			max-width: 100%;
			text-align: center;
		}
		.content{
			background-color: white;
			padding: 30px;
			max-width: 100%;
			min-height: 300px;
		}
		.signature{
			background-color: white;
			padding: 30px;
			max-width: 100%;
			text-align: right;
		}
		p{
			line-height: 1.6;
		}
		.footer{
			background-color: blue;
			color : #FFF;
			padding: 20px;
			max-width: 100%;
			text-align: center;
		}
	</style>
</head>
<body>
	<div class="container">
		<div class="header">
			<h2>PRAKTIKUM CRM - EMAIL</h2>
		</div>
		<div class="content">
			Yth, {nama}
			<p style="text-align: justify;">
				{pesan}
			</p>
			Info : 
			<p>
				{sender_info}
			</p>
		</div>
		<div class="signature">
			{tanggal}<br><br>
			Salam, {pengirim}
		</div>
		<div class="footer">
			<h4>NAMA WEB</h4>
			<p>
				{alamat_pengirim}<br>
				{telepon_pengirim}<br>
				{email_pengirim}<br>
			</p>
		</div>
	</div>
</body>
</html>